# Generated by Django 5.2.1 on 2025-06-24 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CircutorDataDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('valor', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Dato Circutor',
                'verbose_name_plural': 'Datos Circutor',
                'db_table': 'circutor_dia_2025_06',
                'managed': False,
            },
        ),
    ]
