# names.py
names = {
    "TAM 009E": "TAM WICKMAN 5/8\"-6",
    "TAM 008E": "TAM WICKMAN 5/8\"-6",
    "TAM 003E": "TAM SCHUTTE SE-25",
    "TAM 002E": "TAM WICKMAN 2 1/4\"-6",
    "TAM 001E": "TAM WICKMAN 2 1/4 \"-6",
    "TCN 016E": "TCN SCHUTTE SF20",
    "TCN 015E": "TCN SHIMADA B6-16NC",
    "TCN 014E": "TCN JINN FA JSL-20RBY",
    "TCN 013E": "TCN JINN FA JSL-20RBY",
    "TCN 011E": "TCN JINN FA JCL-42TGM",
    "TCN 010E": "TCN JINN FA JSL-32AB",
    "TCN 009E": "TCN JINN FA JSL-32AB",
    "TCN 001E": "TCN LEADWELL LTC- 10BP",
    "TAU 019E": "TAU ERGOMAT TD26 E",
    "TAU 018E": "TAU ERGOMAT A25 E",
    "TAU 001E": "TAU TRAUB A-25"
}

machine_to_area_subarea = {
    # PRODUCCION FORJA
    "PFR 005E": {"area": "PRODUCCION FORJA", "subarea": "prensa friccion"},
    "PFR 001E": {"area": "PRODUCCION FORJA", "subarea": "prensa friccion"},
    "PFR 003E": {"area": "PRODUCCION FORJA", "subarea": "prensa friccion"},
    "PEM 009E": {"area": "PRODUCCION FORJA", "subarea": "prensa troquelada"},
    "PEM 007E": {"area": "PRODUCCION FORJA", "subarea": "prensa troquelada"},
    "PEM 016E": {"area": "PRODUCCION FORJA", "subarea": "forjado"},
    "PEM 015E": {"area": "PRODUCCION FORJA", "subarea": "forjado"},

    # PRODUCCION LLAVES
    "PEH 001E": {"area": "PRODUCCION LLAVES", "subarea": "troquealado"},
    "PEN 004E": {"area": "PRODUCCION LLAVES", "subarea": "troquealado"},
    "FAL 014E": {"area": "PRODUCCION LLAVES", "subarea": "fresado"},
    "FAL 009E": {"area": "PRODUCCION LLAVES", "subarea": "fresado"},
    "FAL 015E": {"area": "PRODUCCION LLAVES", "subarea": "fresado"},
    "FAL 007E": {"area": "PRODUCCION LLAVES", "subarea": "fresado"},
    "FAL 008E": {"area": "PRODUCCION LLAVES", "subarea": "fresado"},
    "FAL 016E": {"area": "PRODUCCION LLAVES", "subarea": "fresado"},
    "FAL 010E": {"area": "PRODUCCION LLAVES", "subarea": "fresado"},
    "PEM 017E": {"area": "PRODUCCION LLAVES", "subarea": "perforado"},
    "PEM 018E": {"area": "PRODUCCION LLAVES", "subarea": "perforado"},
    "PHE 005E": {"area": "PRODUCCION LLAVES", "subarea": "estampado"},
    "PHE 002E": {"area": "PRODUCCION LLAVES", "subarea": "estampado"},
    "PHE 004E": {"area": "PRODUCCION LLAVES", "subarea": "estampado"},
    "DOL 002E": {"area": "PRODUCCION LLAVES", "subarea": "dorsado"},

    # PRODUCCION MAESTRANZA
    "TPA 013E": {"area": "PRODUCCION MAESTRANZA", "subarea": "torno"},
    "TPA 002E": {"area": "PRODUCCION MAESTRANZA", "subarea": "torno"},
    "TPA 011E": {"area": "PRODUCCION MAESTRANZA", "subarea": "torno"},
    "TPA 004E": {"area": "PRODUCCION MAESTRANZA", "subarea": "torno"},
    "TPA 008E": {"area": "PRODUCCION MAESTRANZA", "subarea": "torno"},
    "FUM 002E": {"area": "PRODUCCION MAESTRANZA", "subarea": "fresadoras"},
    "FUM 003E": {"area": "PRODUCCION MAESTRANZA", "subarea": "fresadoras"},
    "REP 001E": {"area": "PRODUCCION MAESTRANZA", "subarea": "maq.convecional"},
    "REP 002E": {"area": "PRODUCCION MAESTRANZA", "subarea": "maq.convecional"},
    "AFU 002E": {"area": "PRODUCCION MAESTRANZA", "subarea": "maq.convecional"},

    # PRODUCCION SERIADA (existentes + nuevos)
    "TAM 001E": {"area": "PRODUCCION SERIADA", "subarea": "multihusillo"},
    "TAM 009E": {"area": "PRODUCCION SERIADA", "subarea": "multihusillo"},
    "TCN 016E": {"area": "PRODUCCION SERIADA", "subarea": "multihusillo"},
    "TAM 002E": {"area": "PRODUCCION SERIADA", "subarea": "multihusillo"},
    "TPA 015E": {"area": "PRODUCCION SERIADA", "subarea": "multihusillo"},
    "TAM 008E": {"area": "PRODUCCION SERIADA", "subarea": "multihusillo"},
    "TAM 003E": {"area": "PRODUCCION SERIADA", "subarea": "multihusillo"},
    "TAU 018E": {"area": "PRODUCCION SERIADA", "subarea": "t.automatico"},
    "TAU 001E": {"area": "PRODUCCION SERIADA", "subarea": "t.automatico"},
    "TAU 019E": {"area": "PRODUCCION SERIADA", "subarea": "t.automatico"},
    "PEM 003E": {"area": "PRODUCCION SERIADA", "subarea": "prensas"},
    "PEM 004E": {"area": "PRODUCCION SERIADA", "subarea": "prensas"},
    "PEN 002E": {"area": "PRODUCCION SERIADA", "subarea": "prensas"},
    "PHV 001E": {"area": "PRODUCCION SERIADA", "subarea": "prensas"},
    "PHV 003E": {"area": "PRODUCCION SERIADA", "subarea": "prensas"},
    "PHV 002E": {"area": "PRODUCCION SERIADA", "subarea": "prensas"},
    "PEM 002E": {"area": "PRODUCCION SERIADA", "subarea": "prensas"},
    "PNV 001E": {"area": "PRODUCCION SERIADA", "subarea": "prensas"},
    "PEN 001E": {"area": "PRODUCCION SERIADA", "subarea": "prensas"},
    "PEM 001E": {"area": "PRODUCCION SERIADA", "subarea": "prensas"},
    "PNV 002E": {"area": "PRODUCCION SERIADA", "subarea": "prensas"},
    "PNV 004E": {"area": "PRODUCCION SERIADA", "subarea": "prensas"},
    "TCN 014E": {"area": "PRODUCCION SERIADA", "subarea": "t.cnc"},
    "TCN 013E": {"area": "PRODUCCION SERIADA", "subarea": "t.cnc"},
    "TCN 001E": {"area": "PRODUCCION SERIADA", "subarea": "t.cnc"},
    "TCN 011E": {"area": "PRODUCCION SERIADA", "subarea": "t.cnc"},
    "TCN 010E": {"area": "PRODUCCION SERIADA", "subarea": "t.cnc"},
    "TCN 009E": {"area": "PRODUCCION SERIADA", "subarea": "t.cnc"},
    "TCN 015E": {"area": "PRODUCCION SERIADA", "subarea": "t.cnc"},
    "TRO 005E": {"area": "PRODUCCION SERIADA", "subarea": "taladro"},
    "TAC 001E": {"area": "PRODUCCION SERIADA", "subarea": "taladro"},
    "TVN 002E": {"area": "PRODUCCION SERIADA", "subarea": "taladro"},
    "TAB 006E": {"area": "PRODUCCION SERIADA", "subarea": "taladro"},
    "TAC 002E": {"area": "PRODUCCION SERIADA", "subarea": "taladro"},
    "TRO 004E": {"area": "PRODUCCION SERIADA", "subarea": "taladro"},
    "TAF 003E": {"area": "PRODUCCION SERIADA", "subarea": "taladro"},
    "TAC 005E": {"area": "PRODUCCION SERIADA", "subarea": "taladro"},
    "COA 001E": {"area": "PRODUCCION SERIADA", "subarea": "taladro"},
    "TRO 003E": {"area": "PRODUCCION SERIADA", "subarea": "taladro"},
    "TRE 010E": {"area": "PRODUCCION SERIADA", "subarea": "revolver"},
    "TRE 004E": {"area": "PRODUCCION SERIADA", "subarea": "revolver"},
    "TRE 002E": {"area": "PRODUCCION SERIADA", "subarea": "revolver"},
    "TSA 002E": {"area": "PRODUCCION SERIADA", "subarea": "t.semiautomatico"},
    "TSA 003E": {"area": "PRODUCCION SERIADA", "subarea": "t.semiautomatico"},
    "TSA 001E": {"area": "PRODUCCION SERIADA", "subarea": "t.semiautomatico"},
    "TTV 003E": {"area": "PRODUCCION SERIADA", "subarea": "transfers"},
    "TTH 004E": {"area": "PRODUCCION SERIADA", "subarea": "transfers"},
    "TTH 001E": {"area": "PRODUCCION SERIADA", "subarea": "transfers"},
    "TTH 002E": {"area": "PRODUCCION SERIADA", "subarea": "transfers"},
    "TTV 001E": {"area": "PRODUCCION SERIADA", "subarea": "transfers"},
    "TTV 002E": {"area": "PRODUCCION SERIADA", "subarea": "transfers"},
    "TTH 005E": {"area": "PRODUCCION SERIADA", "subarea": "transfers"},
}